version: '3'

services:
  mysql:
    container_name: calendar_db
    image: mysql/mysql-server:8.0.30
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: "calendar_db"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"