spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/calendar_db?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update